In [1]:
from pydantic import BaseModel, Field

In [2]:
class Irisinput(BaseModel):
    sepal_length: float = Field(gt=4, lt=8.5)
    sepal_width: float = Field(gt=1.8, lt=5)
    petal_length: float = Field(gt=0.8, lt=7.5)
    petal_width: float = Field(gt=0, lt=3)

Irisinput

__main__.Irisinput

In [4]:
# to check validation within class 'Irisinput'. any number outside of range will result in
# a validation error
Irisinput(sepal_length=4.2, sepal_width=2.5, petal_length=0.9, petal_width=1)

Irisinput(sepal_length=4.2, sepal_width=2.5, petal_length=0.9, petal_width=1.0)

In [5]:
payload = Irisinput(sepal_length=4.2, sepal_width=2.5, petal_length=0.9, petal_width=1)
payload

Irisinput(sepal_length=4.2, sepal_width=2.5, petal_length=0.9, petal_width=1.0)

In [6]:
#'model_dump()' returns a dictionary representation of the model
# this dict-representation model we can now make into Dataframe
payload.model_dump()

{'sepal_length': 4.2,
 'sepal_width': 2.5,
 'petal_length': 0.9,
 'petal_width': 1.0}

In [7]:
import pandas as pd 

# model as Dataframe
pd.DataFrame(payload)

              0    1
0  sepal_length  4.2
1   sepal_width  2.5
2  petal_length  0.9
3   petal_width  1.0

In [8]:
pd.DataFrame(payload.model_dump(), index=[0])

   sepal_length  sepal_width  petal_length  petal_width
0           4.2          2.5           0.9          1.0

### check if endpoint works using httpx

In [9]:
import httpx

url = "http://127.0.0.1:8000/api/iris/v1/predict"

payload = {
  "sepal_length": 4.1,
  "sepal_width": 1.9,
  "petal_length": 6.9,
  "petal_width": 2.8
}
with httpx.Client(timeout=10) as client:
    response = client.post(url, json= payload)
    response.raise_for_status()
    
response

In [10]:
response.json()

{'predicted_flower': 'Iris-virginica'}