## LanceDB -  a vectordatabase for LLM applications

In [1]:
import lancedb

db = lancedb.connect(uri="vector_database")
db

LanceDBConnection(uri='/Users/susannarokka/Desktop/NBI_year_2/Repo/AI_Engineering_OPA24_Susanna_Rokka/code-alongs/13_lancedb/vector_database')

In [2]:
db.uri

'/Users/susannarokka/Desktop/NBI_year_2/Repo/AI_Engineering_OPA24_Susanna_Rokka/code-alongs/13_lancedb/vector_database'

## Create a table

In [5]:
import json
with open("animals_text_embedded.json", "r") as file:
    data= json.loads(file.read())

data

[{'text': 'A small brown dog running.', 'vector': [0.12, 0.85, 0.33]},
 {'text': 'A cat resting quietly on a sofa.', 'vector': [0.4, 0.91, 0.1]},
 {'text': 'A large gray elephant drinking water.',
  'vector': [0.88, 0.22, 0.55]},
 {'text': 'A fast cheetah sprinting across the savannah.',
  'vector': [0.95, 0.12, 0.72]},
 {'text': 'A colorful parrot perched on a branch.',
  'vector': [0.25, 0.66, 0.81]},
 {'text': 'A frog sitting on a lily pad.', 'vector': [0.14, 0.44, 0.27]}]

In [ ]:
table_animals = db.create_table("animals_text_embedded.json", exist_ok=True, data=data)
# add mode= "overwrite" for another version in vector_database
table_animals

LanceTable(name='animals_text_embedded.json', version=1, _conn=LanceDBConnection(uri='/Users/susannarokka/Desktop/NBI_year_2/Repo/AI_Engineering_OPA24_Susanna_Rokka/code-alongs/13_lancedb/vector_database'))

In [7]:
import pandas

table_animals.to_pandas()

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]

## Add more data to vector database

In [8]:
more_data = [
    {"text": "A panda eating bamboo peacefully.", "vector": [0.51, 0.37, 0.82]},
    {"text": "A lion roaring loudly on a rock.", "vector": [0.93, 0.18, 0.41]},
]
table_animals.add(more_data)

AddResult(version=2)

In [9]:
table_animals.to_pandas()

                                            text              vector
0                     A small brown dog running.  [0.12, 0.85, 0.33]
1               A cat resting quietly on a sofa.    [0.4, 0.91, 0.1]
2          A large gray elephant drinking water.  [0.88, 0.22, 0.55]
3  A fast cheetah sprinting across the savannah.  [0.95, 0.12, 0.72]
4         A colorful parrot perched on a branch.  [0.25, 0.66, 0.81]
5                  A frog sitting on a lily pad.  [0.14, 0.44, 0.27]
6              A panda eating bamboo peacefully.  [0.51, 0.37, 0.82]
7               A lion roaring loudly on a rock.  [0.93, 0.18, 0.41]

## Create an empty table and then delete it